# Generated by Django 5.0.4 on 2024-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(default='Базовое описание товара', max_length=200)),
                ('colors', models.ManyToManyField(to='MainApp.color')),
            ],
        ),
    ]
